[Service]
Environment=LD_LIBRARY_PATH=/home/corexia/corexia-ia/env/lib/python3.11/site-packages/nvidia/cublas/lib:/home/corexia/corexia-ia/env/lib/python3.11/site-packages/nvidia/cufft/lib:/home/corexia/corexia-ia/env/lib/python3.11/site-packages/nvidia/cuda_runtime/lib:/home/corexia/corexia-ia/env/lib/python3.11/site-packages/nvidia/cuda_nvrtc/lib
